import createClient from 'openapi-fetch';
import type { paths } from './types.d'; // This file will be generated by the npm script!

// Creates an API fetch wrapper completely synchronized to the backend Node server's Zod schemas
export const apiClient = createClient<paths>({ baseUrl: 'http://localhost:4000' });
